[package]
name = "fstsed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true
lto = "fat"
codegen-units = 1

[dependencies]
anyhow = "1.0.63"
bstr = "0.2.17"
camino = "1.1"
clap = { version = "3.2.20", features = ["derive", "cargo"] }
fst = "0.4"
grep-cli = "0.1.6"
itermore = "0.2.0"
lazy_static = "1.4.0"
memchr = "2.5.0"
memmap2 = "0.5.7"
microtemplate = "1.0.3"
regex = "1.6.0"
serde_json = "1.0.85"
termcolor = "1.1.2"
