[package]
name = "fstsed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true
lto = "fat"
codegen-units = 1

[dependencies]
anyhow = "1.0.68"
bstr = "1.0.1"
camino = "1.1.2"
clap = { version = "4.1.4", features = ["derive", "cargo"] }
fst = "0.4"
grep-cli = "0.1.7"
itermore = { version = "0.5.0",  default-features = false, features = ["array_chunks"]}
lazy_static = "1.4.0"
memchr = "2.5.0"
memmap2 = "0.5.8"
microtemplate = "1.0.3"
regex = "1.7.1"
serde_json = "1.0.91"
termcolor = "1.2.0"
